# Archivo docker-compose para definir un stack de contenedores para un lago de datos 
# Creado por: Abel coronado https://github.com/abxda/datalake4os
# Modifcado por: Irving cabrera https://github.com/irvcaza/datalake4os

version: "3"

services:
######### Capa de data storage #########
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data


######### Capa de data virtualization #########

  database:
    container_name: hive-database
    image: postgres:12
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive

  hive-server:
    container_name: hive-server
    image: hive:3.1.0
    build:
      context: services/hive
      dockerfile: hive.dockerfile
    env_file:
      - ./services/hive/hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      HIVE_SITE_CONF_hive_metastore_uris: "thrift://hive-metastore:9083"
      # https://stackoverflow.com/a/53336873
      HIVE_SITE_CONF_hive_server2_active_passive_ha_enable: "true"
    depends_on: 
      - hive-metastore

  hive-metastore:
    container_name: hive-metastore
    image: hive:3.1.0
    build:
      context: services/hive
      dockerfile: hive.dockerfile
    volumes:
      - "./services/hivemetastore/create-table.hql:/tmp/create-table.hql"
    env_file:
      - ./services/hive/hive.env
    command: hivemetastore
    depends_on: 
      - database

  presto:
    container_name: presto
    image: prestosql/presto:333
    ports:
      - 8080:8080
    volumes:
      - "./services/presto/conf/config.properties:/lib/presto/default/etc/config.properties"
      - "./services/presto/conf/hive.properties:/lib/presto/default/etc/catalog/hive.properties"
      - "./services/presto/conf/query-example.sql:/tmp/query-example.sql"
  
#   atlas:  
#     image: wbaa/rokku-dev-apache-atlas:0.1.5
#       container_name: atlas
#       ports:
#         - 21000:21000
#       networks:
#         - datalake4os-net
#     environment:
#         - ATLAS_KICKSTART_AMUNDSEN=true

#   amundsensearch:
#     build:
#       context: ./services/amundsensearchlibrary
#       dockerfile: public.Dockerfile
#     container_name: amundsensearch
#     ports:
#       - 5001:5001
#     environment:
#       - CREDENTIALS_PROXY_USER=admin
#       - CREDENTIALS_PROXY_PASSWORD=admin
#       - PROXY_ENDPOINT=http://atlas:21000
#       - PROXY_CLIENT=ATLAS
#     networks:
#       - datalake4os-net

#   amundsenmetadata:
#     build:
#       context: ./services/amundsenmetadatalibrary
#       dockerfile: public.Dockerfile
#     container_name: amundsenmetadata
#     ports:
#       - 5002:5002
#     networks:
#       - datalake4os-net      
#     environment:
#       - CREDENTIALS_PROXY_USER=admin
#       - CREDENTIALS_PROXY_PASSWORD=admin
#       - PROXY_HOST=http://atlas
#       - PROXY_PORT=21000
#       - PROXY_CLIENT=ATLAS

#   amundsenfrontend:
#     build:
#       context: ./services/amundsenfrontendlibrary
#       args:
#         SEARCHSERVICE_BASE: http://amundsensearch:5001
#         METADATASERVICE_BASE: http://amundsenmetadata:5002
#       dockerfile: local.Dockerfile
#     container_name: amundsenfrontend
#     depends_on:
#       - amundsenmetadata
#       - amundsensearch
#     ports:
#       - 5000:5000
#     networks:
#       - datalake4os-net   
#     environment:
#       - METADATASERVICE_BASE=http://amundsenmetadata:5002
#       - SEARCHSERVICE_BASE=http://amundsensearch:5001

# networks:
#   default:
#     external:
#       name: datalake4os-net
